# SWA, can be compared to non-swa result from presFeb23 experiment
# For now selected one param setting that showed large variability accross tasks

seml:
  executable: /lustre/groups/ml01/code/karin.hrovatin/cross_species_prediction/notebooks/eval/run_seml.py
  name: csp_eval
  output_dir: /lustre/groups/ml01/workspace/karin.hrovatin/data/cross_species_prediction/eval/swa/logs # CHANGE! OUT!
  project_root_dir:  /lustre/groups/ml01/code/karin.hrovatin/cross_species_prediction/notebooks/eval
  conda_environment: csp
  
slurm:
  sbatch_options_template: GPU
  sbatch_options:
    mem: 10G          # memory, set to 32, for pancreas this could be 10Gb
    cpus-per-task: 4  # num cores, set to 4
    time: 0-02:00     # max time, D-HH:MM, set to 0-08:00, for pancreas this could be 1h
    nice: 10000

fixed:
  path_save: /lustre/groups/ml01/workspace/karin.hrovatin/data/cross_species_prediction/eval/swa/ # CHANGE! OUT!
  system_key: system
  system_translate: 1
  max_epochs: 70
  epochs_detail_plot: 10
  # Model params
  system_decoders: 0
  path_adata: /lustre/groups/ml01/workspace/karin.hrovatin/data/cross_species_prediction/pancreas_example/combined_orthologues.h5ad
  group_key: cell_type_final
  group_translate: beta
  batch_key: study_sample  
  # Params
  z_dist_metric: MSE
  z_distance_cycle_weight: 10
  swa: 1
  lr: 0.01
  
grid:
  seed_num:
    type: choice
    options:
      - 1
      - 2
      - 3
      - 4
      - 5 
  eval_type:
    type: choice
    options:
      - translation
      - integration   
  optimizer:
    type: choice
    options:
      - Adam
      - AdamW
  swa_lr:
    type: choice
    options:
      - 0.01
      - 0.001   